name: ElementCraft
version: 1.0
main: com.yourname.elementcraft.ElementCraft
api-version: 1.20
commands:
  object:
    description: Управление объектами
    usage: /object <create|delete|info|add|remove>